### ISSUE TITLE
Kotlin 1.6

### ISSUE THREAD

**Issue by sunheihei** [ColdTea-Projects/SmplrAlarm#1]
Please adapt to kotlin version 1.6, kotlin version 1.6 does not work properly。

now : ext.kotlin_version = '1.5.31'

https://stackoverflow.com/questions/70056804/moshi-1-12-0-with-kotlin-1-6-0-fails-to-parse-metadata

**Comment by ColdTea-Projects** [comment]
Dear sunheihei,

I ll look into the issue as soon as possible. Thanks for the information.

**Comment by ColdTea-Projects** [comment]
here you go mate 
https://github.com/ColdTea-Projects/SmplrAlarm/releases/tag/2.1.0

enjoy!

@sunheihei

**Comment by sunheihei** [comment]
Hey, I found some problems, when I make a release apk and enable minifyEnabled is true, I get an error: 

java.lang.AssertionError: Missing field in de.coldtea.smplr.smplralarm.models.a

So I think it's the proguard-rules.pro cause, so I did some tests and I think you should probably add this to the proguard-rules.pro file:

-keep class de.coldtea.smplr.smplralarm.models.* {*;}
