### ISSUE TITLE
Click on notification not working

### ISSUE THREAD

**Issue by chiragtalaviya** [ColdTea-Projects/SmplrAlarm#4]
intent { onClickShortcutIntent } not working

**Comment by chiragtalaviya** [comment]
Is there any update?

**Comment by ColdTea-Projects** [comment]
I am sorry I was on vacation for some time, I'll try to look into it this evening. However, can you please meanwhile elaborate and include some more details? Or maybe share a snippet of your code. Thank you!

**Comment by chiragtalaviya** [comment]
![image](https://user-images.githubusercontent.com/25198561/164014890-1150393e-5efa-4f69-8847-a026524ef7ce.png)
![image](https://user-images.githubusercontent.com/25198561/164015018-b67c47da-6f0e-4dda-8e7d-f94285058da5.png)
Thanks for getting back to me. Here is the code snippet. I have setup daily word notification using your library. Everything is fine except notification click. I have already added intent with Activity. I do not require fullscreen intent so I haven't added it.

**Comment by ColdTea-Projects** [comment]
I guess the problem you are facing is about your context. Since the lifecycle you call and receive the alarm are different than each other, the context you assigned is gone already at the point you receive the broadcast. Can you please set your intents with application context and let me know if it works that way.

**Comment by chiragtalaviya** [comment]
I have tried but it is not working.

**Comment by ColdTea-Projects** [comment]
I'll look into it as soon as possible. Sorry for the inconvenience!

**Comment by ColdTea-Projects** [comment]
I fixed the problem in the version 2.1.1. Please test it out and let me know. Also changed the name of the parameter to contentIntent. You can find the explanation in the release notes and at the very bottom of the documentation under the section "(New) 2.1.1 and above"

**Comment by chiragtalaviya** [comment]
It is working fine now.
Thanks.
